exclude: ["README.md", "Gemfile", "Gemfile.lock", "package-lock.json", "package.json", "postinstall.sh"]
markdown: kramdown
title: Chan4077.GitHub.io
url: https://chan4077.github.io
# Enable future posts
future: true
sass:
  style: compressed
  sass_dir: _sass/node_modules
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!-- End of excerpt -->"
      # Custom Jekyll config to enable comments on all blog post pages
      comments: true
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  # Use default configuration
  enabled: true
  tags:
    permalink: '/blog/tagged/:tag'
  categories:
    permalink: '/blog/category/:cat'
plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2
