name: Edric Chan
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
# Timezone - Singapore GMT+8:00
timezone: Asia/Singapore
# Tags
tags: 
- material-design
- angularjs
- angularjs-material
- singapore
- changelog
- whats new
- breaking change
- news
- future
# Options for SCSS compiling
sass:
  style: compressed