exclude: ["README.md"]
markdown: kramdown
title: Chan4077.GitHub.io
future: true
sass:
  style: compressed
  sass_dir: _sass/node_modules
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!-- End of excerpt -->"
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2
