exclude:
  - README.md
  # Node files
  - package-lock.json
  - package.json
  - postinstall.sh
  - workbox-config.js
  - node_modules/*.md
  - art/
include:
  # Explicitly include node_modules
  - node_modules

markdown: kramdown
title: "Edric's website"
url: https://edricchan03.github.io

# Enable future posts
future: true

# Sass config
sass:
  implementation: sass-embedded
  style: compressed
  sass_dir: _sass
  # Note: GitHub Pages does not natively support this option.
  load_paths:
    - _sass
    - node_modules

# Front matter defaults
defaults:
  # node_modules
  - scope:
      path: 'node_modules'
    values:
      # Exclude them from the sitemap
      sitemap: false
  # All posts
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      show_excerpt: true
      excerpt_separator: '<!-- End of excerpt -->'
      # Custom Jekyll config to enable comments on all blog post pages
      comments: true
      # The default author of a post if unset
      author: edric_chan
  # TIL posts
  - scope:
      path: 'til'
      type: 'posts'
    values:
      # Whether to show an excerpt of the post
      # Default: false (hides excerpt)
      show_excerpt: false
  # Authors
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

# Pagination config
pagination:
  # debug: true
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Collections config
collections:
  authors:
    # Output each file in the collection to _site
    output: true
    permalink: /blog/authors/:name

# Autopages config
autopages:
  # Use default configuration
  enabled: true
  tags:
    permalink: '/blog/tagged/:tag'
  categories:
    permalink: '/blog/category/:cat'
  collection:
    enabled: false

# Workbox.js config
workbox:
  sw_src_filepath: 'service-worker.js'
  sw_dest_filename: 'service-worker.js'
  precache_recent_posts_num: 5
  precache_glob_directory: '_site'
  precache_glob_patterns:
    - '**/*.{html,png,css,ico,js}'
  precache_glob_ignores:
    # There aren't any _ prefixed directories when the site is built or when served
    - '_*/**'
    # We only want to cache CSS/JS files
    - 'node_modules/**/*.{html,md}'

# GitHub metadata config
github:
  source:
    branch: website-v2

# Plugins to use
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-workbox-plugin
