exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'package-lock.json', 'package.json', 'postinstall.sh', 'workbox-config.js', 'art/', 'docs/', 'node_modules/*.md']
markdown: kramdown
title: "Edric's website"
url: https://edricchan03.github.io
# Enable future posts
future: true
sass:
  style: compressed
  sass_dir: _sass
  # Note: GitHub Pages does not natively support this option.
  load_paths:
    - _sass
    - node_modules
defaults:
  -
    scope:
      path: 'node_modules'
    values:
      sitemap: false
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      show_excerpt: true
      excerpt_separator: '<!-- End of excerpt -->'
      # Custom Jekyll config to enable comments on all blog post pages
      comments: true
      # The default author of a post if unset
      author: edric_chan
  -
    scope:
      path: 'til'
      type: 'posts'
    values:
      # Whether to show an excerpt of the post
      # Default: false (hides excerpt)
      show_excerpt: false
pagination:
  # debug: true
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  # Use default configuration
  enabled: true
  tags:
    permalink: '/blog/tagged/:tag'
  categories:
    permalink: '/blog/category/:cat'
  collection:
    enabled: false
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
